  const swaggerDefinition = {
  openapi: "3.0.0",
  info: {
    title: "NineLab API",
    version: "1.0.0",
    description: "NineLab API",
  },
  servers: [
    {
      url: "http://localhost:8000",
    },
  ],
  paths:
    /review/add:
      post:
        summary: createReview API
        parameters:
          - userID:
            required: true
            schema:
              String
          - guID:
            required: true
            schema:
              String
          - dongID:
            required: true
            schema:
              String
          - title:
            required: true
            schema:
              String
          - content:
            required: true
            schema:
              String            
        responses:
          '200':
            description: OK
};
